; https://www.linkedin.com/jobs/search/?alertAction=viewjobs&currentJobId=JOB_ID&distance=RADIUS_MILES&f_E=EXP_LEVEL_CODES&f_TPR=rSECONDS&f_WT=WORK_TYPE_CODES&geoId=GEO_ID&keywords=SEARCH_KEYWORDS&location=CITY%2C%20STATE%2C%20COUNTRY&origin=ORIGIN_CONTEXT&sortBy=SORT_METHOD&spellCorrectionEnabled=BOOL

[keywords]
alertAction = viewjobs
currentJobId = 4375620841 
; # of miles
distance = 50 
; # for experience level intern(1) or entry-level(2).
f_E = 1,2
; # of seconds since posted(24h).
f_TPR = r86400
; # for work type: (on-site, remote, hybrid).
f_WT = 1,2,3
keywords = Software Intern
location = Lowell , Massachusetts, United States
; how the user initiated the query.
origin = JOB_SEARCH_PAGE_JOB_FILTER
; relevance
sortBy = R
spellCorrectionEnabled = true
